# Site settings
title: Dashboard
email: Ken@Volometrix.com
# baseurl: "/projects/volometrix/gene" # the subpath of your site, e.g. /blog/
baseurl: "/rvp" # the subpath of your site, e.g. /blog/
# url: "http://ux.corp.volometrix.com" # the base hostname & protocol for your site
# url: "http://gyroscopestudios.com"
url: "https://gyrostu.github.io"
twitter_username: gyrostu
github_username:  gyrostu

# Collections
collections:
  components:
    output: false

# Build settings
markdown: kramdown